---
version: "3.7"
networks:
  app:
    driver: bridge

services:
  app:
    build: .

    volumes:
      - .:/var/www/:cached

    ports:
      - "80:80"

    networks:
      - app

    environment:
      TEST_ENV: foo
